version: "2"
services:
  inbox:
      build: .
      working_dir: /app
      ports:
        - "5000:80"
      environment:
        DB_URL: "postgresql://inbox:password@db:5432/inbox?sslmode=disable"
      depends_on:
        - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: inbox
